### ISSUE TITLE
Use custom policies in request/response processing

### ISSUE THREAD

**Issue by MarlosChida** [CAAPIM/Android-MAS-SDK#248]
Greetings everyone.  I was reading the source code in order to know better how the SDK works to develop a Demo APP and came to know PolicyManager.java (com.ca.mas.core.policy.PolicyManager). 

I couldn't find any documentation about the use of custom policies when a request/response is processed (here and at mas.ca.com), but It seems ready and there's an "official"  way to do It already implemented in PolicyManager.java. The code loops into a custom policies variable, set by the property "PROP_ADD_CUSTOM_POLICIES" (wich has the value "msso.add.custom.policies"),  and adds them before adding the Default Policies (Classes "xxxAssertion"). 

"PROP_ADD_CUSTOM_POLICIES" is set in MobileSsoConfig.java, which states that "PROP_ADD_CUSTOM_POLICIES"  is an "ArrayList of String. Add a list of custom policies to intercept the Default Policy execution.".

The only places I found setting this properties were DefaultConfiguration.java and ConfigurationManager.java. Following the code logic, "PROP_ADD_CUSTOM_POLICIES" should probably be defined in  Config.java,  at "public static Config[] values = {..." using the same pattern as the other settings, and set at ConfigurationManager.java's create method ("conf.putProperty(attr.key, getValue(attr, jsonObject));".

So, after all this analysis, I could't find a way to use this feature. Setting "msso.add.custom.policies" in my msso_config.json with my custom policy class name doesn't work, as the property is never read and set, per my debugs. Maybe I missed something, or this feature is not ready for use now, but the foundations are set.

I would appreciate any comments, thoughts and directions on this question.

I have a fully configured and licensed CA API Gateway to do any testing required.

**Comment by witrisna** [comment]
Hi,

Sorry for late response.
The PolicyManager and Custom policy are designed for internal use, and the custom policy is no longer supported in current SDK version. 

Can you share your use case with us? sounds like you want to intercept the API request with custom logic, do you think com.ca.mas.foundation.MASConnectionListener can help in your scenario?

**Comment by MarlosChida** [comment]
Hi, sorry too for the late response. As per the inline documentation, It seemed to me that this feature was avaliable to developers, not only for internal use. I tried using MASConnectionListener and It worked, thanks.
