### ISSUE TITLE
Enhancement - Encryption of tokens when AMS storage is used

### ISSUE THREAD

**Issue by mishkakipi** [CAAPIM/Android-MAS-SDK#254]
Tokens (access, refresh and id) are currently stored base64 encoded in AMS.
Encryption keys may be derived from client_id and/or client_secret obtained during device initialization (used symmetrically or asymmetrically)
Another option is the key pair generated for device-id

**Comment by witrisna** [comment]
This is a feature in our backlog, will bring this to the team and see if we can give a higher priority for this feature. 
Thanks for the advice.

**Comment by mishkakipi** [comment]
Thanks, for the feedback.
Could you update if you were able to push this feature with the team and maybe a timeline for delivery?

**Comment by ramellocarina** [comment]
The team is currently working on this feature and we are hoping to deliver it as part of 1.8 release. We don't have a precise timeline to share at the moment.
