### ISSUE TITLE
CA Mobile SDK (MAG/MAS) - SNI Client Support

### ISSUE THREAD

**Issue by MarlosChida** [CAAPIM/Android-MAS-SDK#268]
This is not an issue, just a question.

We are implementing MAS/MAG/RAS SDK at a customer, and to fulfill some networking infrastructure requirements (Firewall/WAF/Reverse Proxy...) our customer is asking if the "Mobile SDK for CA Mobile API Gateway" (https://mas.ca.com) supports SNI (Server Name Indication).

We couldn't find this information in the official documentation.

By our searches in the Official Documentation and CA Communities site, we believe that CA API Gateway (Server) does not have SNI support, but the question above is specific for the Mobile Client SDK (Android/iOS/etc).

If the Mobile Client SDK supports SNI,  we need to know if there is any limitation in any of the supported Operating Systems.

Best Regards,

Marlos Chida

**Comment by witrisna** [comment]
The developer can override the default hostname verification with the SDK, here is an example:

MAS.setConnectionListener(new MASConnectionListener() {
    @Override
    public void onObtained(HttpURLConnection connection) {
        ((HttpsURLConnection) connection).setHostnameVerifier(new HostnameVerifier() {
            @Override
            public boolean verify(String hostname, SSLSession session) {
                //Provide the logic to verify the hostname, reture true to accept the hostname, false to reject.
            }
        });
    }

    @Override
    public void onConnected(HttpURLConnection connection) {

    }
});

Detail of the interface can be found under: https://developer.android.com/reference/javax/net/ssl/HttpsURLConnection.html#setDefaultHostnameVerifier(javax.net.ssl.HostnameVerifier)

Thank you.

**Comment by MarlosChida** [comment]
Hi,

   I think my question was misunderstood, or I'm having trouble understanding your answer.
 
  SNI can be described as:
-----------
SNI stands for Server Name Indication and is an extension of the TLS protocol. It indicates which hostname is being contacted by the browser (client) at the beginning of the 'handshake'-process.
This allows a server to present multiple certificates on the same IP address and TCP port number and hence allows multiple secure websites to be served off the same IP address without requiring all those sites to use the same certificate.
-----------

   What I want to know is:

  In  the above scenario (SNI-enabled server serving multiple HTTPS hosts), if a client using MAS SDK connects to this server, it will, during TLS handshake, provide server name information to the server, which, in turn, will present the righ SSL certificate to the SDK? 

Meaning "does MAS SDK HTTP(S) Client Libraries supports and uses SNI by default?"

Thanks again,

Marlos Chida

**Comment by witrisna** [comment]
Sorry, I may misunderstand your question.
The MAG SDK use native Android HttpsURLConnection, 
According to the documentation from Android: https://developer.android.com/training/articles/security-ssl

> Fortunately, HttpsURLConnection supports SNI since Android 2.3. One workaround if you need to support Android 2.2 (and older) is to set up an alternative virtual host on a unique port so that it's unambiguous which server certificate to return."

The HttpsURLConnection should support SNI.
Do you experience any issue using the SDK in your environment?

**Comment by MarlosChida** [comment]
I am not experiencing any issues using the Client SDK.

My customer was concerned about compatibility with some network architecture aspects of the implementation.

Thank you very much for the fast answer.

I will now seek for the same answer from iOS SDK team.

Thanks again,

Marlos Chida
