### ISSUE TITLE
Issue with Shared Storage

### ISSUE THREAD

**Issue by ecousino** [CAAPIM/Android-MAS-SDK#322]
Hi, i am using the MASFoundation.Xamarin 1.9, downloaded from the nuget packages in Visual Studio. After configuring the Secure Account Manager Storage, when i try to start the SDK, i get the following error:
`Error:Java.Lang.RuntimeException:java.lang.reflect.InvocationTargetException ---> Java.Lang.Reflect.InvocationTargetException:Exception of type 'Java.Lang.Reflect.InvocationTargetException' was thrown. ---> Com.CA.Mas.Foundation.MASSharedStorageException:uid 10382 cannot explicitly add accounts of type: @2131492947 --- End of inner exception stack trace ---...`

Here is a snippet from msso_config.json:
`"mobile_sdk": {
      "sso_enabled": true,
      "location_enabled": true,
      "location_provider": "network",
      "msisdn_enabled": true,
      "enable_public_key_pinning": false,
      "trusted_public_pki": false,
      "trusted_cert_pinned_public_key_hashes": [],
      "client_cert_rsa_keybits": 1024,
      "storage": {
        "class": "com.ca.mas.core.datasource.MASSecureStorageDataSource"
      }
    },`

Here is my authenticator.xml:
`<account-authenticator xmlns:android="http://schemas.android.com/apk/res/android"		 
  android:accountType="@string/acc_name"
  android:icon="@drawable/logo"
  android:smallIcon="@drawable/logo_small"		 
  android:label="@string/app_name"/>`

Here is my manifest file:
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.TallerMAG" android:installLocation="auto">
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.AUTHENTICATE_ACCOUNTS" />
	<uses-permission android:name="android.permission.USE_CREDENTIALS" />
	<uses-permission android:name="android.permission.GET_ACCOUNTS" />
	<uses-permission android:name="android.permission.MANAGE_ACCOUNTS" />
	<uses-permission android:name="android.permission.ACCOUNT_MANAGER" />
<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="27" />
	<application android:label="TallerMAG.Android">
		<service android:name="com.ca.mas.core.storage.sharedstorage.MASAuthenticatorService" android:exported="false">
			<intent-filter>
				<action android:name="android.accounts.AccountAuthenticator" />
			</intent-filter>
			<meta-data android:name="account.name" android:resource="@string/acc_name" />
			<meta-data android:name="android.accounts.AccountAuthenticator" android:resource="@xml/authenticator" />
		</service>
	</application>
</manifest>`

And the exception is thrown by invoking `MAS.Start(activity,true)`

Any ideas about where am i doing it wrong?

**Comment by rodrigoareis** [comment]
Hi,

with given information, there are some ways that could potentially cause that issue. We would need to ask you to provide a bit more information of the application using the SDK. However, before start to investigate this issue, we would like to request you to confirm if the sample app provided in the Xamarin repository ([https://github.com/CAAPIM/Xamarin-MAS-Foundation/tree/master/sample/Android/BasicAuthSample)](https://github.com/CAAPIM/Xamarin-MAS-Foundation/tree/master/sample/Android/BasicAuthSample)) shows the same issue.

Please note that this is a public GitHub repository, if you are the customer of CA Technologies, we can deal with this issue through CA Support channel. We will need to request more details about your system environment and app that will be used to investigate further on this issue.

**Comment by ecousino** [comment]
I've opened a support case,
Thank you @rodrigoareis
